/**:
  ros__parameters:
    # 串口配置
    control_serial:      # 控制命令串口
      port: "/dev/ttyUSB0"  # 串口设备名
      baud_rate: 115200     # 波特率
      timeout: 0.1          # 超时时间(秒)
      
    encoder_serial:      # 编码器数据串口
      port: "/dev/ttyUSB1"  # 串口设备名
      baud_rate: 115200     # 波特率
      timeout: 0.1          # 超时时间(秒)

    # 速度参数配置
    velocity:
      # 线速度配置
      linear:
        x:
          offset: 0.0       # Vx偏移量
          max: 1.0          # Vx最大值
        y:
          offset: 0.0       # Vy偏移量
          max: 1.0          # Vy最大值
      
      # 角速度配置
      angular:
        z:
          offset: 0.0       # Wz偏移量
          max: 1.0          # Wz最大值

    # 机器人物理参数
    robot:
      wheel_radius: 0.05      # 轮子半径(m)
      wheel_distance_x: 0.2   # 轴距(前后轮中心距离，单位m)
      wheel_distance_y: 0.25  # 轮距(左右轮中心距离，单位m)
      encoder_resolution: 4096 # 编码器分辨率(脉冲/转)
      mecanum_angle: 45.0     # 麦克纳姆轮滚子安装角度(度)

    # 其他配置
    odom:
      frame_id: "odom"        # 里程计坐标系
      child_frame_id: "base_link"  # 机器人坐标系
      publish_tf: true        # 是否发布TF变换

    # 调试模式
    debug: false            # 调试模式开关 