/**:
  ros__parameters:
    # 串口配置
    control_serial:      # 控制命令串口
      port: "/dev/ttyACM0"  # 串口设备名，更新为检测到的设备
      baud_rate: 115200     # 波特率
      timeout: 0.1          # 超时时间(秒)
      
    encoder_serial:      # 编码器数据串口
      port: "/dev/ttyACM0"  # 串口设备名，更新为检测到的设备
      baud_rate: 9600       # 波特率，设置为设备检测到的9600
      timeout: 0.1          # 超时时间(秒)

    # 速度参数配置
    velocity:
      # 线速度配置
      linear:
        x:
          offset: 0.0       # Vx偏移量
          max: 1.0          # Vx最大值(m/s)，会被映射到DJI范围
        y:
          offset: 0.0       # Vy偏移量
          max: 1.0          # Vy最大值(m/s)，会被映射到DJI范围
      
      # 角速度配置
      angular:
        z:
          offset: 0.0       # Wz偏移量
          max: 1.0          # Wz最大值(rad/s)，会被映射到DJI范围

    # 机器人物理参数
    robot:
      wheel_radius: 0.05      # 轮子半径(m)
      wheel_distance_x: 0.2   # 轴距(前后轮中心距离，单位m)
      wheel_distance_y: 0.25  # 轮距(左右轮中心距离，单位m)
      encoder_resolution: 4096 # 编码器分辨率(脉冲/转)
      mecanum_angle: 45.0     # 麦克纳姆轮滚子安装角度(度)

    # 其他配置
    odom:
      frame_id: "odom"        # 里程计坐标系
      child_frame_id: "base_link"  # 机器人坐标系
      publish_tf: true        # 是否发布TF变换

    # 调试模式
    debug: true               # 调试模式开关，启用以查看更多信息
    protocol_debug: true      # 协议调试模式，打印16进制数据
    debug_print_interval: 0.5  # 调试信息打印间隔(秒)，降低间隔以更频繁地查看数据 